# Generated by Django 4.0.4 on 2022-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required', max_length=255, verbose_name='delivery name')),
                ('price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'Price must be between 0 and 999'}}, help_text='Required', max_digits=5, verbose_name='delivery price')),
                ('method', models.CharField(choices=[('IS', 'In Store'), ('HD', 'Home Delivery'), ('DD', 'Digital Delivery')], help_text='Required', max_length=255, verbose_name='delivery method')),
                ('timeframe', models.CharField(help_text='Required', max_length=255, verbose_name='delivery timeframe')),
                ('window', models.CharField(help_text='Required', max_length=255, verbose_name='delivery window')),
                ('order_self', models.IntegerField(default=0, help_text='Required', verbose_name='list order')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Delivery Option',
                'verbose_name_plural': 'Delivery Options',
            },
        ),
    ]
