# Generated by Django 4.0.4 on 2022-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='delivery_instructions',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Instructions'),
        ),
    ]
